name: Freetz-NG hosttools build

on:
  push:
    paths:
      - 'toolchain/**'
      - '.github/**'
  pull_request:
    paths:
      - 'toolchain/**'
      - '.github/**'
  
jobs:  
  build:
    runs-on: ubuntu-latest
    container: 
      image: pfichtner/freetz:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v2
    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v2
      with:
        path: .freetz-dl
        key: ${{ runner.os }}-downloads

    - name: Build toolchain
      run: |
        # for demo
        # date >foo.txt && mkdir bar ; date >bar/bar.txt 
        tools/dl-hosttools

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: ncipollo/release-action@v1
      with:
        # for demo
        # artifacts: "foo.txt,bar/*.txt"
        artifacts: "dl/*"
        # variable has content but 40 chars of hex are not allowed by "release"
        # tag: ${{ github.sha }}
        tag: hosttools-${{ steps.date.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
