name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3 * * *'

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
        upstream_repository: Freetz-NG/freetz-ng
        upstream_branch: master
        target_branch: master
