name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3 * * *'

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: master
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: Freetz-NG/freetz-ng
        upstream_sync_branch: master
