name: Freetz-NG CI

on:
  push:
    paths:
      - 'toolchain/**'
      - '.github/**'
  pull_request:
    paths:
      - 'toolchain/**'
      - '.github/**'
  
jobs:  
  build:
    runs-on: ubuntu-latest
    container: 
      image: pfichtner/freetz:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'Freetz-NG/freetz-ng'
        path: 'freetz-ng'
    - uses: actions/checkout@v2
      with:
        path: 'configs'
    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v2
      with:
        path: freetz-ng/dl
        key: ${{ runner.os }}-downloads

    - name: Build toolchain
      run: |
        # for demo
        # cd freetz-ng && date >foo.txt && mkdir bar ; date >bar/bar.txt 
        cd freetz-ng && tools/dl-toolchains_make

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: ncipollo/release-action@v1
      with:
        # for demo
        # artifacts: "freetz-ng/foo.txt,freetz-ng/bar/*.txt"
        artifacts: "dl/*"
        # variable has content but 40 chars of hex are not allowed by "release"
        # tag: ${{ github.sha }}
        tag: release-${{ steps.date.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
